language: cpp

dist: trusty
sudo: require

services:
- docker

install:
- docker build -t vega .

script:
- docker run -t -w="/opt/vega/build_gcc" vega ./tests
- docker run -t -w="/opt/vega/build_clang" vega ./tests
